export type SupportedLanguage = 'en' | 'ru' | 'ka' | 'es' | 'uk' | 'pl' | 'hi' | 'am' | 'fr' | 'pa';

const translations: Record<string, Record<string, string>> = {
  // Nav
  'nav.map': { en: 'Map', ru: 'Карта', ka: 'რუკა', es: 'Mapa', uk: 'Карта', pl: 'Mapa', hi: 'नक्शा', am: 'ካርታ', fr: 'Carte', pa: 'ਨਕਸ਼ਾ' },
  'nav.channels': { en: 'Channels', ru: 'Каналы', ka: 'არხები', es: 'Canales', uk: 'Канали', pl: 'Kanały', hi: 'चैनल', am: 'ቻናሎች', fr: 'Canaux', pa: 'ਚੈਨਲ' },
  'nav.messages': { en: 'Messages', ru: 'Сообщения', ka: 'შეტყობინებები', es: 'Mensajes', uk: 'Повідомлення', pl: 'Wiadomości', hi: 'संदेश', am: 'መልዕክቶች', fr: 'Messages', pa: 'ਸੁਨੇਹੇ' },
  'nav.profile': { en: 'Profile', ru: 'Профиль', ka: 'პროფილი', es: 'Perfil', uk: 'Профіль', pl: 'Profil', hi: 'प्रोफ़ाइल', am: 'መገለጫ', fr: 'Profil', pa: 'ਪ੍ਰੋਫਾਈਲ' },

  // Status
  'status.available': { en: 'Available', ru: 'Доступен', ka: 'ხელმისაწვდომი', es: 'Disponible', uk: 'Доступний', pl: 'Dostępny', hi: 'उपलब्ध', am: 'ዝግጁ', fr: 'Disponible', pa: 'ਉਪਲਬਧ' },
  'status.driving': { en: 'Driving', ru: 'В пути', ka: 'მგზავრობაში', es: 'Conduciendo', uk: 'В дорозі', pl: 'W trasie', hi: 'ड्राइविंग', am: 'በመንዳት ላይ', fr: 'En route', pa: 'ਡ੍ਰਾਈਵਿੰਗ' },
  'status.resting': { en: 'Resting', ru: 'Отдыхает', ka: 'ისვენებს', es: 'Descansando', uk: 'Відпочиває', pl: 'Odpoczynek', hi: 'आराम', am: 'ዕረፍት', fr: 'Repos', pa: 'ਆਰਾਮ' },
  'status.dnd': { en: 'Do Not Disturb', ru: 'Не беспокоить', ka: 'არ შემაწუხოთ', es: 'No molestar', uk: 'Не турбувати', pl: 'Nie przeszkadzać', hi: 'परेशान न करें', am: 'አትረብሹ', fr: 'Ne pas déranger', pa: 'ਪਰੇਸ਼ਾਨ ਨਾ ਕਰੋ' },

  // Auth
  'auth.signIn': { en: 'Sign In', ru: 'Войти', ka: 'შესვლა', es: 'Iniciar sesión', uk: 'Увійти', pl: 'Zaloguj się', hi: 'साइन इन', am: 'ግባ', fr: 'Connexion', pa: 'ਸਾਈਨ ਇਨ' },
  'auth.signUp': { en: 'Create Account', ru: 'Создать аккаунт', ka: 'ანგარიშის შექმნა', es: 'Crear cuenta', uk: 'Створити акаунт', pl: 'Utwórz konto', hi: 'खाता बनाएं', am: 'መለያ ፍጠር', fr: 'Créer un compte', pa: 'ਖਾਤਾ ਬਣਾਓ' },
  'auth.signOut': { en: 'Sign Out', ru: 'Выйти', ka: 'გამოსვლა', es: 'Cerrar sesión', uk: 'Вийти', pl: 'Wyloguj', hi: 'साइन आउट', am: 'ውጣ', fr: 'Déconnexion', pa: 'ਸਾਈਨ ਆਊਟ' },
  'auth.email': { en: 'Email', ru: 'Эл. почта', ka: 'ელ.ფოსტა', es: 'Correo', uk: 'Ел. пошта', pl: 'E-mail', hi: 'ईमेल', am: 'ኢሜይል', fr: 'E-mail', pa: 'ਈਮੇਲ' },
  'auth.password': { en: 'Password', ru: 'Пароль', ka: 'პაროლი', es: 'Contraseña', uk: 'Пароль', pl: 'Hasło', hi: 'पासवर्ड', am: 'የይለፍ ቃል', fr: 'Mot de passe', pa: 'ਪਾਸਵਰਡ' },
  'auth.confirmPassword': { en: 'Confirm Password', ru: 'Подтвердите пароль', ka: 'პაროლის დადასტურება', es: 'Confirmar contraseña', uk: 'Підтвердіть пароль', pl: 'Potwierdź hasło', hi: 'पासवर्ड की पुष्टि', am: 'የይለፍ ቃል አረጋግጥ', fr: 'Confirmer le mot de passe', pa: 'ਪਾਸਵਰਡ ਪੁਸ਼ਟੀ' },
  'auth.welcomeBack': { en: 'Welcome back, driver.', ru: 'С возвращением, водитель.', ka: 'კეთილი იყოს შენი დაბრუნება.', es: 'Bienvenido de nuevo, conductor.', uk: 'З поверненням, водій.', pl: 'Witaj ponownie, kierowco.', hi: 'वापसी पर स्वागत है, ड्राइवर।', am: 'እንኳን ደህና መጣህ ሹፌር።', fr: 'Bon retour, chauffeur.', pa: 'ਵਾਪਸੀ ਤੇ ਸਵਾਗਤ ਹੈ, ਡ੍ਰਾਈਵਰ।' },
  'auth.joinNetwork': { en: 'Join the driver network.', ru: 'Присоединяйтесь к сети водителей.', ka: 'შეუერთდით მძღოლთა ქსელს.', es: 'Únete a la red de conductores.', uk: 'Приєднуйтесь до мережі водіїв.', pl: 'Dołącz do sieci kierowców.', hi: 'ड्राइवर नेटवर्क से जुड़ें।', am: 'የሹፌሮች ኔትወርክ ይቀላቀሉ።', fr: 'Rejoignez le réseau de chauffeurs.', pa: 'ਡ੍ਰਾਈਵਰ ਨੈੱਟਵਰਕ ਨਾਲ ਜੁੜੋ।' },
  'auth.noAccount': { en: "Don't have an account?", ru: 'Нет аккаунта?', ka: 'არ გაქვთ ანგარიში?', es: '¿No tienes cuenta?', uk: 'Немає акаунту?', pl: 'Nie masz konta?', hi: 'खाता नहीं है?', am: 'መለያ የለህም?', fr: "Pas de compte ?", pa: 'ਖਾਤਾ ਨਹੀਂ ਹੈ?' },
  'auth.hasAccount': { en: 'Already have an account?', ru: 'Уже есть аккаунт?', ka: 'უკვე გაქვთ ანგარიში?', es: '¿Ya tienes cuenta?', uk: 'Вже маєте акаунт?', pl: 'Masz już konto?', hi: 'पहले से खाता है?', am: 'ቀድሞ መለያ አለህ?', fr: 'Déjà un compte ?', pa: 'ਪਹਿਲਾਂ ਤੋਂ ਖਾਤਾ ਹੈ?' },
  'auth.passwordMismatch': { en: 'Passwords do not match', ru: 'Пароли не совпадают', ka: 'პაროლები არ ემთხვევა', es: 'Las contraseñas no coinciden', uk: 'Паролі не збігаються', pl: 'Hasła nie pasują', hi: 'पासवर्ड मेल नहीं खाते', am: 'የይለፍ ቃሎች አይዛመዱም', fr: 'Les mots de passe ne correspondent pas', pa: 'ਪਾਸਵਰਡ ਮੇਲ ਨਹੀਂ ਖਾਂਦੇ' },
  'auth.passwordLength': { en: 'Password must be at least 6 characters', ru: 'Пароль должен быть не менее 6 символов', ka: 'პაროლი უნდა იყოს მინიმუმ 6 სიმბოლო', es: 'La contraseña debe tener al menos 6 caracteres', uk: 'Пароль повинен містити щонайменше 6 символів', pl: 'Hasło musi mieć co najmniej 6 znaków', hi: 'पासवर्ड कम से कम 6 अक्षर का होना चाहिए', am: 'የይለፍ ቃል ቢያንስ 6 ፊደላት መሆን አለበት', fr: 'Le mot de passe doit contenir au moins 6 caractères', pa: 'ਪਾਸਵਰਡ ਘੱਟੋ-ਘੱਟ 6 ਅੱਖਰ ਹੋਣਾ ਚਾਹੀਦਾ' },
  'auth.back': { en: 'Back', ru: 'Назад', ka: 'უკან', es: 'Atrás', uk: 'Назад', pl: 'Wstecz', hi: 'वापस', am: 'ተመለስ', fr: 'Retour', pa: 'ਵਾਪਸ' },

  // Onboarding
  'onboarding.title': { en: 'RouteLink', ru: 'RouteLink', ka: 'RouteLink', es: 'RouteLink', uk: 'RouteLink', pl: 'RouteLink', hi: 'RouteLink', am: 'RouteLink', fr: 'RouteLink', pa: 'RouteLink' },
  'onboarding.subtitle': { en: 'Connect with drivers on your route', ru: 'Свяжитесь с водителями на вашем маршруте', ka: 'დაუკავშირდით მძღოლებს თქვენს მარშრუტზე', es: 'Conéctate con conductores en tu ruta', uk: "Зв'яжіться з водіями на вашому маршруті", pl: 'Połącz się z kierowcami na trasie', hi: 'अपने रूट पर ड्राइवरों से जुड़ें', am: 'በመንገድዎ ላይ ከሹፌሮች ጋር ይገናኙ', fr: 'Connectez-vous avec les chauffeurs sur votre route', pa: 'ਆਪਣੇ ਰੂਟ ਤੇ ਡ੍ਰਾਈਵਰਾਂ ਨਾਲ ਜੁੜੋ' },
  'onboarding.getStarted': { en: 'Get Started', ru: 'Начать', ka: 'დაწყება', es: 'Comenzar', uk: 'Почати', pl: 'Rozpocznij', hi: 'शुरू करें', am: 'ጀምር', fr: 'Commencer', pa: 'ਸ਼ੁਰੂ ਕਰੋ' },
  'onboarding.alreadyDriver': { en: 'Already a driver? Sign In', ru: 'Уже водитель? Войти', ka: 'უკვე მძღოლი ხართ? შესვლა', es: '¿Ya eres conductor? Inicia sesión', uk: 'Вже водій? Увійти', pl: 'Już jesteś kierowcą? Zaloguj', hi: 'पहले से ड्राइवर हैं? साइन इन करें', am: 'ቀድሞ ሹፌር ነህ? ግባ', fr: 'Déjà chauffeur ? Connectez-vous', pa: 'ਪਹਿਲਾਂ ਤੋਂ ਡ੍ਰਾਈਵਰ ਹੋ? ਸਾਈਨ ਇਨ ਕਰੋ' },
  'onboarding.feature1': { en: "See who's on your route right now", ru: 'Узнайте, кто сейчас на вашем маршруте', ka: 'ნახეთ ვინ არის თქვენს მარშრუტზე', es: 'Ve quién está en tu ruta ahora', uk: 'Дивіться хто зараз на вашому маршруті', pl: 'Zobacz kto jest na trasie', hi: 'देखें कि अभी आपके रूट पर कौन है', am: 'አሁን በመንገድዎ ላይ ማን እንዳለ ይመልከቱ', fr: 'Voyez qui est sur votre route maintenant', pa: 'ਦੇਖੋ ਹੁਣ ਤੁਹਾਡੇ ਰੂਟ ਤੇ ਕੌਣ ਹੈ' },
  'onboarding.feature2': { en: 'Real-time route channels & chat', ru: 'Чаты маршрутов в реальном времени', ka: 'რეალურ დროში მარშრუტის არხები და ჩატი', es: 'Canales de ruta y chat en tiempo real', uk: 'Канали маршруту та чат в реальному часі', pl: 'Kanały tras i czat na żywo', hi: 'रीयल-टाइम रूट चैनल और चैट', am: 'በቅጽበት የመንገድ ቻናሎች እና ቻት', fr: 'Canaux de route et chat en temps réel', pa: 'ਰੀਅਲ-ਟਾਈਮ ਰੂਟ ਚੈਨਲ ਅਤੇ ਚੈਟ' },
  'onboarding.feature3': { en: 'Voice rooms for your highway', ru: 'Голосовые комнаты для вашей трассы', ka: 'ხმოვანი ოთახები თქვენი მაგისტრალისთვის', es: 'Salas de voz para tu autopista', uk: 'Голосові кімнати для вашої траси', pl: 'Pokoje głosowe dla twojej trasy', hi: 'आपके हाइवे के लिए वॉयस रूम', am: 'ለአውራ ጎዳናዎ የድምፅ ክፍሎች', fr: 'Salons vocaux pour votre autoroute', pa: 'ਤੁਹਾਡੇ ਹਾਈਵੇ ਲਈ ਵੌਇਸ ਰੂਮ' },

  // Onboarding carousel
  'onboarding.s1.title': { en: 'Never drive alone', ru: 'Никогда не ездите один', ka: 'არასდროს იმგზავრო მარტო', es: 'Nunca conduzcas solo', uk: 'Ніколи не їдь сам', pl: 'Nigdy nie jedź sam', hi: 'कभी अकेले न चलाएं', am: 'ብቻህን አትንዳ', fr: 'Ne conduisez jamais seul', pa: 'ਕਦੇ ਇਕੱਲੇ ਨਾ ਚਲਾਓ' },
  'onboarding.s1.text': { en: 'Connect with drivers on your exact route in real time.', ru: 'Связывайтесь с водителями на вашем маршруте в реальном времени.', ka: 'რეალურ დროში დაუკავშირდით მძღოლებს თქვენს ზუსტ მარშრუტზე.', es: 'Conéctate con conductores en tu ruta exacta en tiempo real.', uk: "Зв'язуйтесь з водіями на вашому маршруті в реальному часі.", pl: 'Połącz się z kierowcami na twojej trasie w czasie rzeczywistym.', hi: 'रीयल टाइम में अपने सटीक रूट पर ड्राइवरों से जुड़ें।', am: 'በቅጽበት በትክክለኛ መንገድዎ ላይ ከሹፌሮች ጋር ይገናኙ።', fr: 'Connectez-vous avec les chauffeurs sur votre route exacte en temps réel.', pa: 'ਰੀਅਲ ਟਾਈਮ ਵਿੱਚ ਆਪਣੇ ਸਹੀ ਰੂਟ ਤੇ ਡ੍ਰਾਈਵਰਾਂ ਨਾਲ ਜੁੜੋ।' },
  'onboarding.s2.title': { en: 'Your language, your crew', ru: 'Ваш язык, ваша команда', ka: 'თქვენი ენა, თქვენი გუნდი', es: 'Tu idioma, tu equipo', uk: 'Твоя мова, твоя команда', pl: 'Twój język, twoja ekipa', hi: 'आपकी भाषा, आपकी टीम', am: 'ቋንቋህ ቡድንህ', fr: 'Votre langue, votre équipe', pa: 'ਤੁਹਾਡੀ ਭਾਸ਼ਾ, ਤੁਹਾਡੀ ਟੀਮ' },
  'onboarding.s2.text': { en: 'Chat in English, Spanish, French, Hindi, Punjabi, and more.', ru: 'Общайтесь на английском, русском, испанском и других языках.', ka: 'ისაუბრეთ ინგლისურად, ესპანურად, ფრანგულად და სხვა.', es: 'Chatea en inglés, español, francés, hindi, punyabí y más.', uk: 'Спілкуйтесь англійською, іспанською, французькою, хінді та іншими мовами.', pl: 'Rozmawiaj po angielsku, hiszpańsku, francusku, hindi i nie tylko.', hi: 'अंग्रेजी, स्पेनिश, फ्रेंच, हिंदी, पंजाबी और अन्य भाषाओं में चैट करें।', am: 'በእንግሊዝኛ በስፓኒሽ በፈረንሳይኛ በሂንዲ እና በሌሎችም ቋንቋዎች ያወሩ።', fr: 'Discutez en anglais, espagnol, français, hindi, pendjabi et plus.', pa: 'ਅੰਗ੍ਰੇਜ਼ੀ, ਸਪੈਨਿਸ਼, ਫ੍ਰੈਂਚ, ਹਿੰਦੀ, ਪੰਜਾਬੀ ਅਤੇ ਹੋਰ ਭਾਸ਼ਾਵਾਂ ਵਿੱਚ ਚੈਟ ਕਰੋ।' },
  'onboarding.s3.title': { en: "Voice when you can't type", ru: 'Голос, когда не можете печатать', ka: 'ხმა, როცა ვერ წერთ', es: 'Voz cuando no puedes escribir', uk: 'Голос, коли не можеш писати', pl: 'Głos, gdy nie możesz pisać', hi: 'जब टाइप न कर सकें तो आवाज़', am: 'መጻፍ ሳትችል ድምፅ', fr: 'La voix quand vous ne pouvez pas taper', pa: 'ਜਦੋਂ ਟਾਈਪ ਨਹੀਂ ਕਰ ਸਕਦੇ ਤਾਂ ਆਵਾਜ਼' },
  'onboarding.s3.text': { en: 'Send voice messages, join voice rooms, and stay hands-free on the road.', ru: 'Отправляйте голосовые сообщения и оставайтесь свободными за рулём.', ka: 'გაგზავნეთ ხმოვანი შეტყობინებები და დარჩით თავისუფალი გზაზე.', es: 'Envía mensajes de voz, únete a salas de voz y mantén las manos libres.', uk: 'Надсилайте голосові повідомлення та залишайтеся вільними за кермом.', pl: 'Wysyłaj wiadomości głosowe i bądź wolny na drodze.', hi: 'वॉयस मैसेज भेजें, वॉयस रूम में शामिल हों और हैंड्स-फ्री रहें।', am: 'የድምፅ መልዕክቶች ላኩ የድምፅ ክፍሎች ይቀላቀሉ።', fr: 'Envoyez des messages vocaux, rejoignez des salons et gardez les mains libres.', pa: 'ਵੌਇਸ ਮੈਸੇਜ ਭੇਜੋ, ਵੌਇਸ ਰੂਮ ਵਿੱਚ ਸ਼ਾਮਲ ਹੋਵੋ ਅਤੇ ਹੈਂਡਜ਼-ਫ੍ਰੀ ਰਹੋ।' },
  'onboarding.next': { en: 'Next', ru: 'Далее', ka: 'შემდეგი', es: 'Siguiente', uk: 'Далі', pl: 'Dalej', hi: 'अगला', am: 'ቀጣይ', fr: 'Suivant', pa: 'ਅਗਲਾ' },

  // Chat
  'chat.message': { en: 'Message...', ru: 'Сообщение...', ka: 'შეტყობინება...', es: 'Mensaje...', uk: 'Повідомлення...', pl: 'Wiadomość...', hi: 'संदेश...', am: 'መልዕክት...', fr: 'Message...', pa: 'ਸੁਨੇਹਾ...' },
  'chat.send': { en: 'Send', ru: 'Отправить', ka: 'გაგზავნა', es: 'Enviar', uk: 'Надіслати', pl: 'Wyślij', hi: 'भेजें', am: 'ላክ', fr: 'Envoyer', pa: 'ਭੇਜੋ' },
  'chat.noMessages': { en: "You're the first one here! Say hello and others on this route will see your message.", ru: 'Вы первый! Поздоровайтесь, и другие на маршруте увидят ваше сообщение.', ka: 'თქვენ პირველი ხართ! მოისალმეთ და სხვები ნახავენ.', es: '¡Eres el primero! Saluda y otros conductores verán tu mensaje.', uk: 'Ви перший! Привітайтеся, і інші побачать ваше повідомлення.', pl: 'Jesteś pierwszy! Przywitaj się, a inni zobaczą twoją wiadomość.', hi: 'आप पहले हैं! नमस्ते कहें और इस रूट पर अन्य लोग आपका संदेश देखेंगे।', am: 'የመጀመሪያው እርስዎ ነዎት! ሰላም ይበሉ።', fr: 'Vous êtes le premier ! Dites bonjour et les autres verront votre message.', pa: 'ਤੁਸੀਂ ਪਹਿਲੇ ਹੋ! ਹੈਲੋ ਕਹੋ ਅਤੇ ਇਸ ਰੂਟ ਤੇ ਹੋਰ ਤੁਹਾਡਾ ਸੁਨੇਹਾ ਦੇਖਣਗੇ।' },
  'chat.sendFailed': { en: 'Message failed to send. Check your connection and try again.', ru: 'Не удалось отправить. Проверьте подключение.', ka: 'გაგზავნა ვერ მოხერხდა. შეამოწმეთ კავშირი.', es: 'Error al enviar. Verifica tu conexión.', uk: 'Не вдалося надіслати. Перевірте підключення.', pl: 'Wysyłanie nieudane. Sprawdź połączenie.', hi: 'संदेश भेजने में विफल। कनेक्शन जांचें।', am: 'መልዕክት መላክ አልተሳካም። ግንኙነትዎን ያረጋግጡ።', fr: "Échec de l'envoi. Vérifiez votre connexion.", pa: 'ਸੁਨੇਹਾ ਭੇਜਣ ਵਿੱਚ ਅਸਫਲ। ਕਨੈਕਸ਼ਨ ਜਾਂਚੋ।' },
  'chat.loadFailed': { en: 'Failed to load messages. Please try again.', ru: 'Не удалось загрузить сообщения.', ka: 'შეტყობინებების ჩატვირთვა ვერ მოხერხდა.', es: 'Error al cargar mensajes.', uk: 'Не вдалося завантажити повідомлення.', pl: 'Nie udało się załadować wiadomości.', hi: 'संदेश लोड करने में विफल।', am: 'መልዕክቶችን መጫን አልተሳካም።', fr: 'Échec du chargement des messages.', pa: 'ਸੁਨੇਹੇ ਲੋਡ ਕਰਨ ਵਿੱਚ ਅਸਫਲ।' },
  'chat.24hBanner': { en: 'Showing messages from the last 24 hours', ru: 'Показаны сообщения за последние 24 часа', ka: 'ნაჩვენებია ბოლო 24 საათის შეტყობინებები', es: 'Mostrando mensajes de las últimas 24 horas', uk: 'Показані повідомлення за останні 24 години', pl: 'Wiadomości z ostatnich 24 godzin', hi: 'पिछले 24 घंटों के संदेश दिखा रहे हैं', am: 'ባለፉት 24 ሰዓታት ውስጥ ያሉ መልዕክቶች', fr: 'Messages des dernières 24 heures', pa: 'ਪਿਛਲੇ 24 ਘੰਟਿਆਂ ਦੇ ਸੁਨੇਹੇ ਦਿਖਾ ਰਹੇ ਹਾਂ' },
  'chat.retry': { en: 'Retry', ru: 'Повторить', ka: 'ხელახლა', es: 'Reintentar', uk: 'Повторити', pl: 'Ponów', hi: 'पुनः प्रयास', am: 'ድገም', fr: 'Réessayer', pa: 'ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼' },
  'chat.sending': { en: 'Sending...', ru: 'Отправка...', ka: 'იგზავნება...', es: 'Enviando...', uk: 'Надсилання...', pl: 'Wysyłanie...', hi: 'भेज रहे हैं...', am: 'በመላክ ላይ...', fr: 'Envoi...', pa: 'ਭੇਜ ਰਿਹਾ...' },
  'chat.liveChannel': { en: 'Live Channel', ru: 'Живой канал', ka: 'პირდაპირი არხი', es: 'Canal en vivo', uk: 'Живий канал', pl: 'Kanał na żywo', hi: 'लाइव चैनल', am: 'ቀጥታ ቻናል', fr: 'Canal en direct', pa: 'ਲਾਈਵ ਚੈਨਲ' },
  'chat.startConversation': { en: 'Send a message to start the conversation', ru: 'Отправьте сообщение, чтобы начать беседу', ka: 'გაგზავნეთ შეტყობინება საუბრის დასაწყებად', es: 'Envía un mensaje para iniciar la conversación', uk: 'Надішліть повідомлення, щоб почати розмову', pl: 'Wyślij wiadomość, aby rozpocząć rozmowę', hi: 'बातचीत शुरू करने के लिए संदेश भेजें', am: 'ውይይት ለመጀመር መልዕክት ላኩ', fr: 'Envoyez un message pour commencer', pa: 'ਗੱਲਬਾਤ ਸ਼ੁਰੂ ਕਰਨ ਲਈ ਸੁਨੇਹਾ ਭੇਜੋ' },
  'chat.deliveredSilently': { en: 'Message (delivered silently)...', ru: 'Сообщение (тихая доставка)...', ka: 'შეტყობინება (ჩუმად მიწოდებული)...', es: 'Mensaje (entrega silenciosa)...', uk: 'Повідомлення (тиха доставка)...', pl: 'Wiadomość (cicha dostawa)...', hi: 'संदेश (चुपचाप डिलीवर)...', am: 'መልዕክት (በዝምታ የተላከ)...', fr: 'Message (livré silencieusement)...', pa: 'ਸੁਨੇਹਾ (ਚੁੱਪ-ਚਾਪ ਡਿਲੀਵਰ)...' },
  'chat.dndBanner': { en: 'This driver is on DND. Your message will be delivered silently.', ru: 'Этот водитель на DND. Ваше сообщение будет доставлено беззвучно.', ka: 'ეს მძღოლი DND-ზეა. თქვენი შეტყობინება ჩუმად მიეწოდება.', es: 'Este conductor está en No molestar. Tu mensaje se entregará en silencio.', uk: 'Цей водій на DND. Ваше повідомлення буде доставлено беззвучно.', pl: 'Ten kierowca jest na DND. Twoja wiadomość zostanie dostarczona cicho.', hi: 'यह ड्राइवर DND पर है। आपका संदेश चुपचाप डिलीवर होगा।', am: 'ይህ ሹፌር DND ላይ ነው። መልዕክትዎ በዝምታ ይደርሳል።', fr: 'Ce chauffeur est en mode NPD. Votre message sera livré silencieusement.', pa: 'ਇਹ ਡ੍ਰਾਈਵਰ DND ਤੇ ਹੈ। ਤੁਹਾਡਾ ਸੁਨੇਹਾ ਚੁੱਪ-ਚਾਪ ਡਿਲੀਵਰ ਹੋਵੇਗਾ।' },

  // Channels
  'channels.title': { en: 'Route Channels', ru: 'Каналы маршрутов', ka: 'მარშრუტის არხები', es: 'Canales de ruta', uk: 'Канали маршрутів', pl: 'Kanały tras', hi: 'रूट चैनल', am: 'የመንገድ ቻናሎች', fr: 'Canaux de route', pa: 'ਰੂਟ ਚੈਨਲ' },
  'channels.myChannels': { en: 'My Channels', ru: 'Мои каналы', ka: 'ჩემი არხები', es: 'Mis canales', uk: 'Мої канали', pl: 'Moje kanały', hi: 'मेरे चैनल', am: 'የእኔ ቻናሎች', fr: 'Mes canaux', pa: 'ਮੇਰੇ ਚੈਨਲ' },
  'channels.allChannels': { en: 'All Channels', ru: 'Все каналы', ka: 'ყველა არხი', es: 'Todos los canales', uk: 'Всі канали', pl: 'Wszystkie kanały', hi: 'सभी चैनल', am: 'ሁሉም ቻናሎች', fr: 'Tous les canaux', pa: 'ਸਾਰੇ ਚੈਨਲ' },
  'channels.join': { en: 'Join', ru: 'Вступить', ka: 'გაწევრიანება', es: 'Unirse', uk: 'Приєднатися', pl: 'Dołącz', hi: 'जुड़ें', am: 'ተቀላቀል', fr: 'Rejoindre', pa: 'ਜੁੜੋ' },
  'channels.leave': { en: 'Leave', ru: 'Выйти', ka: 'დატოვება', es: 'Salir', uk: 'Вийти', pl: 'Opuść', hi: 'छोड़ें', am: 'ውጣ', fr: 'Quitter', pa: 'ਛੱਡੋ' },
  'channels.openChat': { en: 'Open Chat', ru: 'Открыть чат', ka: 'ჩატის გახსნა', es: 'Abrir chat', uk: 'Відкрити чат', pl: 'Otwórz czat', hi: 'चैट खोलें', am: 'ቻት ክፈት', fr: 'Ouvrir le chat', pa: 'ਚੈਟ ਖੋਲੋ' },
  'channels.noJoined': { en: 'No channels joined yet.', ru: 'Вы ещё не подключены к каналам.', ka: 'ჯერ არცერთ არხში არ ხართ.', es: 'Aún no te has unido a canales.', uk: 'Ви ще не приєднались до каналів.', pl: 'Nie dołączyłeś do żadnego kanału.', hi: 'अभी तक कोई चैनल नहीं जुड़ा।', am: 'ገና ምንም ቻናል አልተቀላቀሉም።', fr: "Aucun canal rejoint pour l'instant.", pa: 'ਅਜੇ ਕੋਈ ਚੈਨਲ ਨਹੀਂ ਜੁੜਿਆ।' },
  'channels.noAvailable': { en: 'No channels available.', ru: 'Каналы не найдены.', ka: 'არხები არ არის.', es: 'No hay canales disponibles.', uk: 'Каналів немає.', pl: 'Brak dostępnych kanałów.', hi: 'कोई चैनल उपलब्ध नहीं।', am: 'ምንም ቻናል የለም።', fr: 'Aucun canal disponible.', pa: 'ਕੋਈ ਚੈਨਲ ਉਪਲਬਧ ਨਹੀਂ।' },
  'channels.yourRoute': { en: '📍 Your route', ru: '📍 Ваш маршрут', ka: '📍 თქვენი მარშრუტი', es: '📍 Tu ruta', uk: '📍 Ваш маршрут', pl: '📍 Twoja trasa', hi: '📍 आपका रूट', am: '📍 መንገድዎ', fr: '📍 Votre route', pa: '📍 ਤੁਹਾਡਾ ਰੂਟ' },

  // DM
  'dm.noMessages': { en: 'No messages yet', ru: 'Сообщений пока нет', ka: 'ჯერ შეტყობინებები არ არის', es: 'Aún no hay mensajes', uk: 'Поки що немає повідомлень', pl: 'Brak wiadomości', hi: 'अभी तक कोई संदेश नहीं', am: 'ገና መልዕክቶች የሉም', fr: 'Pas encore de messages', pa: 'ਅਜੇ ਕੋਈ ਸੁਨੇਹਾ ਨਹੀਂ' },
  'dm.tapDriver': { en: 'Tap a driver on the map to say hello. Drivers near you are always happy to chat.', ru: 'Нажмите на водителя на карте, чтобы начать беседу.', ka: 'დააჭირეთ მძღოლს რუკაზე საუბრის დასაწყებად.', es: 'Toca un conductor en el mapa para saludar.', uk: 'Натисніть на водія на карті, щоб почати розмову.', pl: 'Kliknij kierowcę na mapie, aby się przywitać.', hi: 'नक्शे पर ड्राइवर पर टैप करें। पास के ड्राइवर चैट करने को तैयार हैं।', am: 'ሰላም ለማለት ካርታ ላይ ሹፌር ንኩ።', fr: "Appuyez sur un chauffeur sur la carte pour dire bonjour.", pa: 'ਹੈਲੋ ਕਹਿਣ ਲਈ ਨਕਸ਼ੇ ਤੇ ਡ੍ਰਾਈਵਰ ਤੇ ਟੈਪ ਕਰੋ।' },

  // Profile
  'profile.title': { en: 'Profile', ru: 'Профиль', ka: 'პროფილი', es: 'Perfil', uk: 'Профіль', pl: 'Profil', hi: 'प्रोफ़ाइल', am: 'መገለጫ', fr: 'Profil', pa: 'ਪ੍ਰੋਫਾਈਲ' },
  'profile.save': { en: 'Save Profile', ru: 'Сохранить', ka: 'შენახვა', es: 'Guardar', uk: 'Зберегти', pl: 'Zapisz', hi: 'सेव करें', am: 'አስቀምጥ', fr: 'Enregistrer', pa: 'ਸੇਵ ਕਰੋ' },
  'profile.displayName': { en: 'Display Name', ru: 'Имя', ka: 'სახელი', es: 'Nombre', uk: "Ім'я", pl: 'Nazwa', hi: 'प्रदर्शन नाम', am: 'ስም', fr: "Nom d'affichage", pa: 'ਡਿਸਪਲੇ ਨਾਮ' },
  'profile.truckType': { en: 'Truck Type', ru: 'Тип грузовика', ka: 'სატვირთო ტიპი', es: 'Tipo de camión', uk: 'Тип вантажівки', pl: 'Typ ciężarówki', hi: 'ट्रक प्रकार', am: 'የመኪና ዓይነት', fr: 'Type de camion', pa: 'ਟਰੱਕ ਕਿਸਮ' },
  'profile.bio': { en: 'Bio', ru: 'О себе', ka: 'შესახებ', es: 'Bio', uk: 'Про себе', pl: 'Bio', hi: 'बायो', am: 'ስለ እርስዎ', fr: 'Bio', pa: 'ਬਾਇਓ' },
  'profile.driverStatus': { en: 'Driver Status', ru: 'Статус водителя', ka: 'მძღოლის სტატუსი', es: 'Estado del conductor', uk: 'Статус водія', pl: 'Status kierowcy', hi: 'ड्राइवर स्थिति', am: 'የሹፌር ሁኔታ', fr: 'Statut du chauffeur', pa: 'ਡ੍ਰਾਈਵਰ ਸਥਿਤੀ' },
  'profile.visibility': { en: 'Visibility', ru: 'Видимость', ka: 'ხილვადობა', es: 'Visibilidad', uk: 'Видимість', pl: 'Widoczność', hi: 'दृश्यता', am: 'ታይነት', fr: 'Visibilité', pa: 'ਦਿੱਖ' },
  'profile.settings': { en: 'Settings', ru: 'Настройки', ka: 'პარამეტრები', es: 'Ajustes', uk: 'Налаштування', pl: 'Ustawienia', hi: 'सेटिंग्स', am: 'ቅንብሮች', fr: 'Paramètres', pa: 'ਸੈਟਿੰਗਾਂ' },
  'profile.language': { en: 'Language', ru: 'Язык', ka: 'ენა', es: 'Idioma', uk: 'Мова', pl: 'Język', hi: 'भाषा', am: 'ቋንቋ', fr: 'Langue', pa: 'ਭਾਸ਼ਾ' },
  'profile.createTitle': { en: 'Create Your Profile', ru: 'Создайте профиль', ka: 'შექმენით პროფილი', es: 'Crea tu perfil', uk: 'Створіть профіль', pl: 'Utwórz profil', hi: 'अपना प्रोफ़ाइल बनाएं', am: 'መገለጫዎን ይፍጠሩ', fr: 'Créez votre profil', pa: 'ਆਪਣੀ ਪ੍ਰੋਫਾਈਲ ਬਣਾਓ' },
  'profile.createSubtitle': { en: 'This is how other drivers will see you. Use a nickname if you prefer privacy.', ru: 'Так вас будут видеть другие водители. Используйте ник для конфиденциальности.', ka: 'სხვა მძღოლები ასე დაგინახავენ. გამოიყენეთ მეტსახელი.', es: 'Así te verán otros conductores. Usa un apodo si prefieres privacidad.', uk: 'Так вас бачитимуть інші водії. Використовуйте нік.', pl: 'Tak będą cię widzieć inni kierowcy. Użyj pseudonimu.', hi: 'इस तरह अन्य ड्राइवर आपको देखेंगे। निकनेम का उपयोग करें।', am: 'ሌሎች ሹፌሮች እንዲህ ያዩዎታል። ቅጽል ስም ይጠቀሙ።', fr: "Voici comment les autres chauffeurs vous verront. Utilisez un pseudo si vous préférez.", pa: 'ਹੋਰ ਡ੍ਰਾਈਵਰ ਤੁਹਾਨੂੰ ਇਸ ਤਰ੍ਹਾਂ ਦੇਖਣਗੇ। ਨਿੱਕਨੇਮ ਵਰਤੋ।' },
  'profile.createButton': { en: 'Create Profile & Enter Map', ru: 'Создать профиль и войти на карту', ka: 'პროფილის შექმნა და რუკაზე შესვლა', es: 'Crear perfil y entrar al mapa', uk: 'Створити профіль і перейти до карти', pl: 'Utwórz profil i wejdź na mapę', hi: 'प्रोफ़ाइल बनाएं और मैप में जाएं', am: 'መገለጫ ፍጠር እና ካርታ ክፈት', fr: 'Créer le profil et entrer sur la carte', pa: 'ਪ੍ਰੋਫਾਈਲ ਬਣਾਓ ਅਤੇ ਨਕਸ਼ੇ ਵਿੱਚ ਜਾਓ' },

  // Map
  'map.nearby': { en: 'nearby', ru: 'рядом', ka: 'ახლოს', es: 'cerca', uk: 'поруч', pl: 'w pobliżu', hi: 'पास', am: 'በአቅራቢያ', fr: 'à proximité', pa: 'ਨੇੜੇ' },
  'map.loadingMap': { en: 'Loading map...', ru: 'Загрузка карты...', ka: 'რუკის ჩატვირთვა...', es: 'Cargando mapa...', uk: 'Завантаження карти...', pl: 'Ładowanie mapy...', hi: 'मैप लोड हो रहा है...', am: 'ካርታ በመጫን ላይ...', fr: 'Chargement de la carte...', pa: 'ਨਕਸ਼ਾ ਲੋਡ ਹੋ ਰਿਹਾ...' },
  'map.noDrivers': { en: 'No drivers visible nearby right now. They might have their map visibility turned off, or you may be in a low-traffic area.', ru: 'Поблизости нет видимых водителей. Они могли отключить видимость или район малолюдный.', ka: 'ამჟამად ახლოს მძღოლები არ ჩანს.', es: 'No hay conductores visibles cerca ahora. Pueden tener la visibilidad desactivada.', uk: 'Поблизу немає видимих водіїв. Можливо вони вимкнули видимість.', pl: 'Brak widocznych kierowców w pobliżu.', hi: 'अभी आसपास कोई ड्राइवर दिखाई नहीं दे रहा। शायद उन्होंने विजिबिलिटी बंद कर रखी है।', am: 'አሁን በአቅራቢያ ሹፌሮች አይታዩም።', fr: 'Aucun chauffeur visible à proximité pour le moment.', pa: 'ਹੁਣ ਨੇੜੇ ਕੋਈ ਡ੍ਰਾਈਵਰ ਦਿਖਾਈ ਨਹੀਂ ਦੇ ਰਿਹਾ।' },

  // Driving mode
  'driving.banner': { en: '🚛 Driving Mode — Stay safe, pull over to type', ru: '🚛 Режим вождения — будьте осторожны', ka: '🚛 მართვის რეჟიმი — იყავით ფრთხილად', es: '🚛 Modo conducción — Detente para escribir', uk: '🚛 Режим водіння — будьте обережні', pl: '🚛 Tryb jazdy — zatrzymaj się, by pisać', hi: '🚛 ड्राइविंग मोड — सुरक्षित रहें, टाइप करने के लिए रुकें', am: '🚛 የመንዳት ሁነታ — ጥንቃቄ ያድርጉ', fr: '🚛 Mode conduite — Arrêtez-vous pour taper', pa: '🚛 ਡ੍ਰਾਈਵਿੰਗ ਮੋਡ — ਸੁਰੱਖਿਅਤ ਰਹੋ, ਟਾਈਪ ਕਰਨ ਲਈ ਰੁਕੋ' },
  'driving.parked': { en: "I'm Parked", ru: 'Я припарковался', ka: 'გავჩერდი', es: 'Estoy estacionado', uk: 'Я припаркувався', pl: 'Zaparkowany', hi: 'मैं पार्क हूं', am: 'አቁሜያለሁ', fr: 'Je suis garé', pa: 'ਮੈਂ ਪਾਰਕ ਹਾਂ' },

  // Preset messages
  'preset.traffic': { en: '🛑 Traffic ahead', ru: '🛑 Пробка впереди', ka: '🛑 საცობი წინ', es: '🛑 Tráfico adelante', uk: '🛑 Затор попереду', pl: '🛑 Korek przed nami', hi: '🛑 आगे ट्रैफ़िक', am: '🛑 ትራፊክ ወደፊት', fr: '🛑 Trafic devant', pa: '🛑 ਅੱਗੇ ਟ੍ਰੈਫਿਕ' },
  'preset.cop': { en: '🚔 Cop spotted', ru: '🚔 Полиция впереди', ka: '🚔 პოლიცია', es: '🚔 Policía vista', uk: '🚔 Поліція', pl: '🚔 Policja', hi: '🚔 पुलिस दिखी', am: '🚔 ፖሊስ ታይቷል', fr: '🚔 Police repérée', pa: '🚔 ਪੁਲਿਸ ਦਿਖੀ' },
  'preset.roadClosed': { en: '🚧 Road closed', ru: '🚧 Дорога закрыта', ka: '🚧 გზა დაკეტილია', es: '🚧 Carretera cerrada', uk: '🚧 Дорога закрита', pl: '🚧 Droga zamknięta', hi: '🚧 सड़क बंद', am: '🚧 መንገድ ተዘግቷል', fr: '🚧 Route fermée', pa: '🚧 ਸੜਕ ਬੰਦ' },
  'preset.fuel': { en: '⛽ Need fuel', ru: '⛽ Нужно топливо', ka: '⛽ საწვავი მჭირდება', es: '⛽ Necesito gasolina', uk: '⛽ Потрібне паливо', pl: '⛽ Potrzebuję paliwa', hi: '⛽ ईंधन चाहिए', am: '⛽ ነዳጅ ያስፈልጋል', fr: '⛽ Besoin de carburant', pa: '⛽ ਈਂਧਨ ਚਾਹੀਦਾ' },
  'preset.parking': { en: '🅿️ Good parking', ru: '🅿️ Хорошая парковка', ka: '🅿️ კარგი პარკინგი', es: '🅿️ Buen estacionamiento', uk: '🅿️ Гарна парковка', pl: '🅿️ Dobry parking', hi: '🅿️ अच्छी पार्किंग', am: '🅿️ ጥሩ ማቆሚያ', fr: '🅿️ Bon parking', pa: '🅿️ ਵਧੀਆ ਪਾਰਕਿੰਗ' },
  'preset.ice': { en: '🧊 Ice on road', ru: '🧊 Гололёд', ka: '🧊 ყინული გზაზე', es: '🧊 Hielo en carretera', uk: '🧊 Ожеледиця', pl: '🧊 Lód na drodze', hi: '🧊 सड़क पर बर्फ', am: '🧊 በመንገድ ላይ በረዶ', fr: '🧊 Verglas sur la route', pa: '🧊 ਸੜਕ ਤੇ ਬਰਫ਼' },
  'preset.accident': { en: '🚗💥 Accident ahead', ru: '🚗💥 Авария впереди', ka: '🚗💥 ავარია წინ', es: '🚗💥 Accidente adelante', uk: '🚗💥 Аварія попереду', pl: '🚗💥 Wypadek przed nami', hi: '🚗💥 आगे दुर्घटना', am: '🚗💥 አደጋ ወደፊት', fr: '🚗💥 Accident devant', pa: '🚗💥 ਅੱਗੇ ਹਾਦਸਾ' },
  'preset.restStop': { en: '😴 Rest stop good', ru: '😴 Хорошая стоянка', ka: '😴 კარგი გაჩერება', es: '😴 Parada de descanso buena', uk: '😴 Гарна стоянка', pl: '😴 Dobra stacja odpoczynku', hi: '😴 अच्छा रेस्ट स्टॉप', am: '😴 ጥሩ ማረፊያ', fr: '😴 Bonne aire de repos', pa: '😴 ਵਧੀਆ ਰੈਸਟ ਸਟਾਪ' },

  // Voice
  'voice.title': { en: 'Voice Room', ru: 'Голосовая комната', ka: 'ხმოვანი ოთახი', es: 'Sala de voz', uk: 'Голосова кімната', pl: 'Pokój głosowy', hi: 'वॉयस रूम', am: 'የድምፅ ክፍል', fr: 'Salon vocal', pa: 'ਵੌਇਸ ਰੂਮ' },
  'voice.join': { en: 'Join Voice Room', ru: 'Присоединиться', ka: 'შეუერთდით', es: 'Unirse', uk: 'Приєднатися', pl: 'Dołącz', hi: 'वॉयस रूम में जुड़ें', am: 'ተቀላቀል', fr: 'Rejoindre le salon vocal', pa: 'ਵੌਇਸ ਰੂਮ ਵਿੱਚ ਜੁੜੋ' },
  'voice.mute': { en: 'Mute', ru: 'Без звука', ka: 'დადუმება', es: 'Silenciar', uk: 'Вимкнути', pl: 'Wycisz', hi: 'म्यूट', am: 'ዝጋ', fr: 'Muet', pa: 'ਮਿਊਟ' },
  'voice.unmute': { en: 'Unmute', ru: 'Включить', ka: 'ხმის ჩართვა', es: 'Activar', uk: 'Увімкнути', pl: 'Odcisz', hi: 'अनम्यूट', am: 'ክፈት', fr: 'Réactiver', pa: 'ਅਨਮਿਊਟ' },
  'voice.leave': { en: 'Leave', ru: 'Выйти', ka: 'გასვლა', es: 'Salir', uk: 'Вийти', pl: 'Opuść', hi: 'छोड़ें', am: 'ውጣ', fr: 'Quitter', pa: 'ਛੱਡੋ' },
  'voice.participants': { en: 'Participants', ru: 'Участники', ka: 'მონაწილეები', es: 'Participantes', uk: 'Учасники', pl: 'Uczestnicy', hi: 'प्रतिभागी', am: 'ተሳታፊዎች', fr: 'Participants', pa: 'ਭਾਗੀਦਾਰ' },
  'voice.connecting': { en: 'Connecting…', ru: 'Подключение…', ka: 'დაკავშირება…', es: 'Conectando…', uk: 'Підключення…', pl: 'Łączenie…', hi: 'कनेक्ट हो रहा है…', am: 'በመገናኘት ላይ…', fr: 'Connexion…', pa: 'ਕਨੈਕਟ ਹੋ ਰਿਹਾ…' },
  'voice.notConnected': { en: 'Not connected', ru: 'Не подключено', ka: 'არ არის დაკავშირებული', es: 'No conectado', uk: 'Не підключено', pl: 'Nie połączono', hi: 'कनेक्ट नहीं है', am: 'አልተገናኘም', fr: 'Non connecté', pa: 'ਕਨੈਕਟ ਨਹੀਂ' },

  // Report & Block
  'report.title': { en: 'Report', ru: 'Пожаловаться', ka: 'შეტყობინება', es: 'Reportar', uk: 'Поскаржитися', pl: 'Zgłoś', hi: 'रिपोर्ट', am: 'ሪፖርት', fr: 'Signaler', pa: 'ਰਿਪੋਰਟ' },
  'report.description': { en: 'Why are you reporting this?', ru: 'Почему вы жалуетесь?', ka: 'რატომ აცხადებთ?', es: '¿Por qué reportas esto?', uk: 'Чому ви скаржитесь?', pl: 'Dlaczego zgłaszasz?', hi: 'आप रिपोर्ट क्यों कर रहे हैं?', am: 'ለምን ሪፖርት ያደርጋሉ?', fr: 'Pourquoi signalez-vous ceci ?', pa: 'ਤੁਸੀਂ ਰਿਪੋਰਟ ਕਿਉਂ ਕਰ ਰਹੇ ਹੋ?' },
  'report.submitted': { en: 'Report submitted. Thank you for keeping RouteLink safe.', ru: 'Жалоба отправлена. Спасибо за безопасность.', ka: 'შეტყობინება გაგზავნილია. მადლობა.', es: 'Reporte enviado. Gracias.', uk: 'Скаргу надіслано. Дякуємо.', pl: 'Zgłoszenie wysłane. Dziękujemy.', hi: 'रिपोर्ट सबमिट। धन्यवाद।', am: 'ሪፖርት ተልኳል። እናመሰግናለን።', fr: 'Signalement envoyé. Merci.', pa: 'ਰਿਪੋਰਟ ਭੇਜੀ ਗਈ। ਧੰਨਵਾਦ।' },
  'report.cancel': { en: 'Cancel', ru: 'Отмена', ka: 'გაუქმება', es: 'Cancelar', uk: 'Скасувати', pl: 'Anuluj', hi: 'रद्द करें', am: 'ሰርዝ', fr: 'Annuler', pa: 'ਰੱਦ ਕਰੋ' },
  'block.block': { en: 'Block', ru: 'Заблокировать', ka: 'დაბლოკვა', es: 'Bloquear', uk: 'Заблокувати', pl: 'Zablokuj', hi: 'ब्लॉक', am: 'ዝጋ', fr: 'Bloquer', pa: 'ਬਲਾਕ' },
  'block.unblock': { en: 'Unblock', ru: 'Разблокировать', ka: 'განბლოკვა', es: 'Desbloquear', uk: 'Розблокувати', pl: 'Odblokuj', hi: 'अनब्लॉक', am: 'ክፈት', fr: 'Débloquer', pa: 'ਅਨਬਲਾਕ' },
  'block.blocked': { en: 'User blocked', ru: 'Заблокирован', ka: 'დაბლოკილია', es: 'Bloqueado', uk: 'Заблоковано', pl: 'Zablokowany', hi: 'ब्लॉक किया', am: 'ተዘግቷል', fr: 'Utilisateur bloqué', pa: 'ਬਲਾਕ ਕੀਤਾ' },
  'block.unblocked': { en: 'User unblocked', ru: 'Разблокирован', ka: 'განბლოკილია', es: 'Desbloqueado', uk: 'Розблоковано', pl: 'Odblokowany', hi: 'अनब्लॉक किया', am: 'ተከፍቷል', fr: 'Utilisateur débloqué', pa: 'ਅਨਬਲਾਕ ਕੀਤਾ' },
  'block.blockedUsers': { en: 'Blocked Users', ru: 'Заблокированные', ka: 'დაბლოკილები', es: 'Bloqueados', uk: 'Заблоковані', pl: 'Zablokowani', hi: 'ब्लॉक किए गए', am: 'የተዘጉ', fr: 'Utilisateurs bloqués', pa: 'ਬਲਾਕ ਕੀਤੇ' },
  'block.noBlocked': { en: 'No blocked users', ru: 'Нет заблокированных', ka: 'არ არის', es: 'Sin bloqueados', uk: 'Немає', pl: 'Brak', hi: 'कोई नहीं', am: 'የሉም', fr: 'Aucun utilisateur bloqué', pa: 'ਕੋਈ ਬਲਾਕ ਨਹੀਂ' },
  'block.confirmBlock': { en: "Block this driver? They won't be able to message you.", ru: 'Заблокировать этого водителя?', ka: 'დაბლოკოთ ეს მძღოლი?', es: '¿Bloquear a este conductor?', uk: 'Заблокувати цього водія?', pl: 'Zablokować tego kierowcę?', hi: 'इस ड्राइवर को ब्लॉक करें?', am: 'ይህን ሹፌር ይዝጉ?', fr: 'Bloquer ce chauffeur ?', pa: 'ਇਸ ਡ੍ਰਾਈਵਰ ਨੂੰ ਬਲਾਕ ਕਰੋ?' },

  // Driver Card
  'driverCard.message': { en: 'Message', ru: 'Написать', ka: 'წერა', es: 'Mensaje', uk: 'Написати', pl: 'Napisz', hi: 'संदेश', am: 'መልዕክት', fr: 'Message', pa: 'ਸੁਨੇਹਾ' },
  'driverCard.viewProfile': { en: 'View Profile', ru: 'Профиль', ka: 'პროფილი', es: 'Ver perfil', uk: 'Профіль', pl: 'Profil', hi: 'प्रोफ़ाइल देखें', am: 'መገለጫ ይመልከቱ', fr: 'Voir le profil', pa: 'ਪ੍ਰੋਫਾਈਲ ਦੇਖੋ' },
  'driverCard.textSilent': { en: 'Text (Silent)', ru: 'Тихое сообщение', ka: 'ჩუმი შეტყობინება', es: 'Texto (Silencioso)', uk: 'Тихе повідомлення', pl: 'Wiadomość (cicha)', hi: 'टेक्स्ट (साइलेंट)', am: 'ጽሑፍ (ዝምታ)', fr: 'Texte (Silencieux)', pa: 'ਟੈਕਸਟ (ਸਾਈਲੈਂਟ)' },

  // Offline
  'offline.banner': { en: 'No connection — messages will send when back online', ru: 'Нет соединения — сообщения отправятся после восстановления связи', ka: 'კავშირი არ არის — შეტყობინებები გაიგზავნება ინტერნეტის აღდგენისას', es: 'Sin conexión — los mensajes se enviarán cuando vuelvas a estar en línea', uk: "Немає з'єднання — повідомлення надішлються після відновлення", pl: 'Brak połączenia — wiadomości wyślą się po ponownym połączeniu', hi: 'कोई कनेक्शन नहीं — ऑनलाइन होने पर संदेश भेजे जाएंगे', am: 'ግንኙነት የለም — መስመር ላይ ሲመለሱ መልዕክቶች ይላካሉ', fr: 'Pas de connexion — les messages seront envoyés une fois en ligne', pa: 'ਕੋਈ ਕਨੈਕਸ਼ਨ ਨਹੀਂ — ਔਨਲਾਈਨ ਹੋਣ ਤੇ ਸੁਨੇਹੇ ਭੇਜੇ ਜਾਣਗੇ' },

  // General
  'general.loading': { en: 'Loading...', ru: 'Загрузка...', ka: 'ჩატვირთვა...', es: 'Cargando...', uk: 'Завантаження...', pl: 'Ładowanie...', hi: 'लोड हो रहा है...', am: 'በመጫን ላይ...', fr: 'Chargement...', pa: 'ਲੋਡ ਹੋ ਰਿਹਾ...' },
  'general.error': { en: 'Something went wrong', ru: 'Что-то пошло не так', ka: 'რაღაც არასწორია', es: 'Algo salió mal', uk: 'Щось пішло не так', pl: 'Coś poszło nie tak', hi: 'कुछ गलत हो गया', am: 'የሆነ ስህተት ተከስቷል', fr: "Quelque chose s'est mal passé", pa: 'ਕੁਝ ਗਲਤ ਹੋ ਗਿਆ' },
  'general.signOutConfirm': { en: 'Sign out of RouteLink?', ru: 'Выйти из RouteLink?', ka: 'გამოხვიდეთ RouteLink-იდან?', es: '¿Cerrar sesión de RouteLink?', uk: 'Вийти з RouteLink?', pl: 'Wylogować z RouteLink?', hi: 'RouteLink से साइन आउट करें?', am: 'ከRouteLink ውጣ?', fr: 'Se déconnecter de RouteLink ?', pa: 'RouteLink ਤੋਂ ਸਾਈਨ ਆਊਟ ਕਰੋ?' },
  'general.cancel': { en: 'Cancel', ru: 'Отмена', ka: 'გაუქმება', es: 'Cancelar', uk: 'Скасувати', pl: 'Anuluj', hi: 'रद्द करें', am: 'ሰርዝ', fr: 'Annuler', pa: 'ਰੱਦ ਕਰੋ' },
  'general.save': { en: 'Save', ru: 'Сохранить', ka: 'შენახვა', es: 'Guardar', uk: 'Зберегти', pl: 'Zapisz', hi: 'सेव', am: 'አስቀምጥ', fr: 'Enregistrer', pa: 'ਸੇਵ' },
  'general.hiddenWarning': { en: 'Hidden removes you from the live map entirely.', ru: 'Скрытый режим полностью убирает вас с карты.', ka: 'ფარული რეჟიმი მთლიანად გაგშორებთ რუკიდან.', es: 'Oculto te elimina del mapa en vivo por completo.', uk: 'Прихований режим повністю прибирає вас з карти.', pl: 'Ukryty tryb całkowicie usuwa cię z mapy.', hi: 'हिडन मोड आपको लाइव मैप से पूरी तरह हटा देता है।', am: 'ተደብቋል ከቀጥታ ካርታ ሙሉ በሙሉ ያስወግዱዎታል።', fr: 'Caché vous supprime entièrement de la carte en direct.', pa: 'ਹਿਡਨ ਤੁਹਾਨੂੰ ਲਾਈਵ ਨਕਸ਼ੇ ਤੋਂ ਪੂਰੀ ਤਰ੍ਹਾਂ ਹਟਾ ਦਿੰਦਾ ਹੈ।' },
};

export function getTranslation(key: string, lang: SupportedLanguage = 'en'): string {
  const entry = translations[key];
  if (!entry) return key;
  return entry[lang] || entry.en || key;
}
